replicaCount: 1

image:
  repository: tusproject/tusd
  pullPolicy: IfNotPresent
  tag: "v1.10.0"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: ""
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt-staging"
  hosts:
    - host: sandbox.tarrasque.app
      paths:
        - path: /tus/files(/|$)(.*)
          pathType: Prefix
  tls:
    - secretName: tls-secret-tarrasqueapp-tusd
      hosts:
        - sandbox.tarrasque.app

env:
  - name: AWS_ACCESS_KEY_ID
    value: ""
  - name: AWS_SECRET_ACCESS_KEY
    value: ""
  - name: AWS_REGION
    value: ""
  - name: AWS_S3_ENDPOINT
    value: ""
  - name: AWS_S3_BUCKET
    value: ""

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
