name: 'Deploy api'

on:
  workflow_call:
    inputs:
      ENVIRONMENT:
        required: true
        type: string
      ENVIRONMENT_URL:
        required: true
        type: string
      KUBE_NAMESPACE:
        required: true
        type: string
      HELM_ARGS:
        required: true
        type: string

env:
  DOCKERFILE: apps/api/Dockerfile
  HELM_CHART: api
  IMAGE_NAME: tarrasqueapp/api
  KUBE_DEPLOYMENT: api

jobs:
  deploy-api:
    runs-on: ubuntu-latest

    environment:
      name: ${{ inputs.ENVIRONMENT }}
      url: ${{ inputs.ENVIRONMENT_URL }}/api

    steps:
      - name: Checkout master
        uses: actions/checkout@v3

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DigitalOcean Container Registry with short-lived credentials
        run: doctl registry login --expiry-seconds 1200

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          file: ${{ env.DOCKERFILE }}
          tags: ${{ secrets.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ inputs.ENVIRONMENT }}
          build-args: |
            HOST=${{ inputs.ENVIRONMENT_URL }}
            NODE_ENV=production
            COOKIE_SECRET=${{ secrets.COOKIE_SECRET }}
            JWT_SECRET=${{ secrets.JWT_SECRET }}
            JWT_EXPIRES_IN=${{ secrets.JWT_EXPIRES_IN }}
            SENTRY_ENABLED=${{ secrets.SENTRY_ENABLED }}
            SENTRY_DSN=${{ secrets.SENTRY_DSN }}
            STORAGE_PROVIDER=${{ secrets.STORAGE_PROVIDER }}
            AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_REGION=${{ secrets.AWS_REGION }}
            AWS_S3_ENDPOINT=${{ secrets.AWS_S3_ENDPOINT }}
            AWS_S3_BUCKET=${{ secrets.AWS_S3_BUCKET }}
            AWS_S3_URL=${{ secrets.AWS_S3_URL }}
            DATABASE_URL=${{ secrets.DATABASE_URL }}
            SMTP_HOST=${{ secrets.SMTP_HOST }}
            SMTP_PORT=${{ secrets.SMTP_PORT }}
            SMTP_USERNAME=${{ secrets.SMTP_USERNAME }}
            SMTP_PASSWORD=${{ secrets.SMTP_PASSWORD }}
            SMTP_FROM=${{ secrets.SMTP_FROM }}
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Save DigitalOcean kubeconfig with short-lived credentials
        run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 ${{ secrets.KUBE_CLUSTER }}

      - name: Deploy to DigitalOcean Kubernetes
        run: |
          helm upgrade --install ${{ env.HELM_CHART }} ./helm/${{ env.HELM_CHART }} --namespace ${{ inputs.KUBE_NAMESPACE }} --create-namespace \
            --set image.repository="${{ secrets.REGISTRY }}/${{ env.IMAGE_NAME }}" \
            --set image.tag="${{ inputs.ENVIRONMENT }}" \
            --set env.HOST="${{ inputs.ENVIRONMENT_URL }}" \
            --set env.NODE_ENV="production" \
            --set env.COOKIE_SECRET="${{ secrets.COOKIE_SECRET }}" \
            --set env.JWT_SECRET="${{ secrets.JWT_SECRET }}" \
            --set env.JWT_EXPIRES_IN="${{ secrets.JWT_EXPIRES_IN }}" \
            --set env.SENTRY_ENABLED="${{ secrets.SENTRY_ENABLED }}" \
            --set env.SENTRY_DSN="${{ secrets.SENTRY_DSN }}" \
            --set env.STORAGE_PROVIDER="${{ secrets.STORAGE_PROVIDER }}" \
            --set env.AWS_ACCESS_KEY_ID="${{ secrets.AWS_ACCESS_KEY_ID }}" \
            --set env.AWS_SECRET_ACCESS_KEY="${{ secrets.AWS_SECRET_ACCESS_KEY }}" \
            --set env.AWS_REGION="${{ secrets.AWS_REGION }}" \
            --set env.AWS_S3_ENDPOINT="${{ secrets.AWS_S3_ENDPOINT }}" \
            --set env.AWS_S3_BUCKET="${{ secrets.AWS_S3_BUCKET }}" \
            --set env.AWS_S3_URL="${{ secrets.AWS_S3_URL }}" \
            --set env.DATABASE_URL="${{ secrets.DATABASE_URL }}" \
            --set env.SMTP_HOST="${{ secrets.SMTP_HOST }}" \
            --set env.SMTP_PORT="${{ secrets.SMTP_PORT }}" \
            --set env.SMTP_USERNAME="${{ secrets.SMTP_USERNAME }}" \
            --set env.SMTP_PASSWORD="${{ secrets.SMTP_PASSWORD }}" \
            --set env.SMTP_FROM="${{ secrets.SMTP_FROM }}" \
            ${{ inputs.HELM_ARGS }}

      - name: Verify deployment
        run: kubectl rollout status deployment/${{ env.KUBE_DEPLOYMENT }} --namespace ${{ inputs.KUBE_NAMESPACE }} --timeout 2m
